### ISSUE TITLE
Python 2to3 fixers

### ISSUE THREAD

**Issue by aqua-uru** [H-uru/moul-scripts#114]
Out of interest I had a look at 'fixers' that [2to3](https://docs.python.org/3.8/library/2to3.html) can apply to the Python code. I thought I'd document the results here. Below is a list of all fixers that 2to3 has and how they apply to the repo code. This is excluding the `system` directory as it will be swapped out for Python 3's, I assume. 'Occurrences' are counted by lines changed by the fixer.

Fixer | Occurrences | Files | Optional
---- | ---- | ---- | ----
[`buffer`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-buffer) | 2 | 1: `ki/__init__.py` | Yes
[`dict`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-dict) | 115 | 23 in `./`, `ki/`, `plasma/`
[`except`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-except) | 1 | 1: `nb01UpdateHoodInfoImager.py`
[`exec`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-exec) | 44 | 7 in `./`
[`funcattrs`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-funcattrs) | 7 | 1: `plasma/pch.py`
[`has_key`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-has_key) | 9 | 5 in `./`, `plasma/`
[`idioms`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-idioms) | 439 | 102 in `./`, `plasma/` | Yes
[`import`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-import) | 13 | 5 in `ki/`
[`imports`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-imports) | 14 | 8 in `./`
[`long`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-long) | 6 | 6 in `./`, `ki/`
[`metaclass`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-metaclass) | 1 | 1: `ki/xMarkerGameBrain.py`
[`numliterals`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-numliterals) | 1 | 1: `islmEmgrPhase0.py`
[`print`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-print) | 2172 | 165 in `./`, `plasma/`
[`raise`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-raise) | 6 | 1: `plasma/PlasmaTypes.py`
[`repr`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-repr) | 9 | 2 in `./`
[`types`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-types) | 7 | 2 in `./`
[`unicode`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-unicode) | 354 | 17 in `./`, `ki/`
[`ws_comma`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-ws_comma) | 6328 | 240 in `./`, `ki/`, `plasma/` | Yes
[`xrange`](https://docs.python.org/3.8/library/2to3.html#2to3fixer-xrange) | 20 | 6 in `./`, `ki/`

No files need to be modified for these fixers: `apply`, `asserts`, `basestring`, `execfile`, `filter`, `future`, `getcwdu`, `imports2`, `input`, `intern`, `isinstance`, `itertools_imports`, `itertools`, `map`, `methodattrs`, `ne`, `next`, `nonzero`, `operator`,  `paren`, `raw_input`, `reduce`, `reload`, `renames`, `set_literal`, `standarderror`, `sys_exc`, `throw`, `tuple_params`, `urllib`, `xreadlines`, `zip`.

**Comment by aqua-uru** [comment]
skipped in 2to3-safe:

- unicode
- dict
- xrange
- imports
- types
- long
- metaclass

**Comment by dpogue** [comment]
I assume this has been taken care of in our move to full Python 3.8, if not, please re-open on [H-uru/Plasma](https://github.com/H-uru/Plasma)
